### PR TITLE
Store pulse filter values by user id

### LINKED ISSUE #1566: Pulse - filter values are the same for different users in the one account
### Description
Filter values must be different for different users in the same account. 

### Steps to reproduce

1. Login by the first user in account
2. Press "Pulse" in action box for running VM  
3. Change filter values 
5. Log out
6. Login by the second user in the same account
7. Press "Pulse" in action box for running VM

### Actual result
Filter values of the second user are the same as filter values of the first user in the same account.

### Expected result
Filter values of the second user are not changed. Filter values for different users in the same account are different.

Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Safari version XX
- [x] Opera version XX
- [x] IE version XX
- [x] Edge version XX

### Connected requirement IDs
[REQ_PLS_012]
[REQ_PLS_013]
[REQ_PLS_014]
[REQ_PLS_015]

### Screenshots
case1
case2
case3

### PR DESCRIPTION
**Pull request by andrewbents**
closes #1566

### CODE REVIEW

File: src/app/pulse/vm-pulse/vm-pulse.component.ts [hunk 1]
```diff
@@ -238,39 +230,42 @@ export class VmPulseComponent implements OnInit, OnDestroy {
   }
 
   private initParameters() {
-    this._selectedScale = this.getScale();
-    this._selectedAggregations = this.getAggregations();
-    this._selectedShift = this.getShift();
-    this._shiftAmount = this.getShiftAmount();
+    const persistedParams = this.persistence.readParams();
+
+    this._selectedScale = this.getScale(persistedParams.scaleRange);
```
Comment (pm-Egor-Genning) [inline src/app/pulse/vm-pulse/vm-pulse.component.ts]:
```suggestion
maybe move getScale / getAggregations / getShift
to PulseParamsPersistence
```
