### PR TITLE
fix: update behavior of select buttons in the VM creation dialogs

### LINKED ISSUE #1155: Disable select button for Installation source and SO in VM creation if no elements in the list
### Steps to reproduce
1. Make sure that you do not have any ISOs (you can use a simulator)
2. Open VM creation dialog
3. Open the Installation source selection dialog
4. Go to ISO tab
5. Press select button

### Actual result

Select button exists and after it was pressed an error appears at dialog window but Installation source shows previous selection. I think the same problem will be if there are no templates, but there will be ISO.

### Expected result

I think we should hide button (Service offering dialog hide the Select button if there is no SO in tab) or disable, this needs to discuss with PO. If we do this then an error will not be shown.

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Opera version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

vm_creation_installsource

### Screenshots

Initial form state
screenshot from 2018-07-14 16-35-44
Instalation source dialog with no ISOs and the enabled selection button 
screenshot from 2018-07-14 16-35-55
An error that occurs
screenshot from 2018-07-14 16-36-05
Other behavior on a similar situation in the service offering dialog
screenshot from 2018-07-14 16-36-14

### PR DESCRIPTION
**Pull request by tamazlykar**
Fixes #1155, #1145

### CODE REVIEW

File: src/app/service-offering/service-offering-dialog/service-offering-dialog.component.ts [hunk 1]
```diff
@@ -70,11 +70,17 @@ export class ServiceOfferingDialogComponent implements OnInit, OnChanges {
       && this.isVmRunning;
   }
 
-  public get disableSubmitButton(): boolean {
-    return !this.serviceOffering ||
-      !this.serviceOffering.iscustomized && this.serviceOffering.id === this.serviceOfferingId ||
-      this.serviceOffering.iscustomized && !this.serviceOffering.cpuspeed
-      && !this.serviceOffering.cpunumber && !this.serviceOffering.memory;
+  public isDisableSelectButton(): boolean {
```
Comment (zolotyx) [inline src/app/service-offering/service-offering-dialog/service-offering-dialog.component.ts]: maybe rename to isSubmitButtonDisabled?

File: src/app/vm/vm-creation/template/vm-template-dialog.component.ts [hunk 2]
```diff
@@ -1,47 +1,57 @@
...
+  @Input() selectedOsFamilies: OsFamily[];
+  @Input() selectedGroups: string[];
+  @Input() viewMode: string;
+  @Input() query: string;
+  @Input() groups: TemplateGroup[];
+  @Input() isLoading: boolean;
+  @Input() preselectedTemplate: BaseTemplateModel;
+
+  @Output() viewModeChange = new EventEmitter<string>();
+  @Output() selectedTypesChange = new EventEmitter();
```
Comment (zolotyx) [inline src/app/vm/vm-creation/template/vm-template-dialog.component.ts]: add types to EventEmitters
