### PR TITLE
Login form enchancements

### LINKED ISSUE #1417: Login form enhancements
The following enhancements are proposed for the implementation.

1. Rework error notifications: show one notification for all cases of incorrectly entered data
2. Remove * (required fields) from username, password
3. Remove show/hide for a domain, always show domain
4. Add a throbber for login button. When logging in is proceeded, we will show that the system responds and processes the result.

To discuss

### PR DESCRIPTION
**Pull request by andrewbents**
Closes #1417 

login

### CODE REVIEW

File: src/app/auth/login.component.ts [hunk 1]
```diff
@@ -76,8 +68,11 @@ export class LoginComponent implements OnInit {
   }
 
   private login(username: string, password: string, domain: string): void {
+    this._loading = true;
+
     this.auth
       .login(username, password, domain)
+      .pipe(finalize(() => (this._loading = false)))
       .subscribe(() => this.handleLogin(), error => this.handleError(error));
```
Comment (Vnam92) [inline src/app/auth/login.component.ts]: can be moved into `pipe`
