### PR TITLE
fix(accounts): fix update of the accounts limits

### LINKED ISSUE #1114: Error appers when changing limits of Account with project limit "infinity"
### Steps to reproduce
1. Go to Accounts and open a sidebar of any account that has "infinity" value for "project limit"
2. Change one of the limits and save changes

### Actual result

Error "Unable to execute API command updateresourcelimit due to invalid value Infinity for parameter max" appears

### Expected result

The limit is changed, the error does not appear

### Environment
<pre><code>
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### Connected feature ID

- account_limits_display
- account_limits_change

### PR DESCRIPTION
**Pull request by tamazlykar**
Fixes #1114 #1113

### CODE REVIEW

File: src/app/account/account-container/account-details.container.ts [hunk 1]
```diff
@@ -96,9 +95,28 @@ export class AccountDetailsContainerComponent extends WithUnsubscribe() implemen
...
+      return limit;
+    }
+    return {
+      ...limit,
+      max: Infinity
+    };
+  }
+
+  private setInfinityToNoLimit(limit: ResourceLimit) {
+    const max: number | string = limit.max as number | string;
```
Comment (zolotyx) [inline src/app/account/account-container/account-details.container.ts]: this is strange.
ResourceLimit is an interface with max as a number. You need to follow it. otherwise, do not specify that kind of an interface. Try to pass ResourceLimit[] to onLimitsUpdate

File: src/app/account/account-sidebar/account-limits/account-limits.component.ts [hunk 2]
```diff
@@ -33,13 +42,42 @@ export class AccountLimitsComponent {
     [ResourceType.SecondaryStorage]: 'ACCOUNT_PAGE.CONFIGURATION.SSTORAGE_LIMIT',
   };
 
+  public ngOnChanges(changes: SimpleChanges) {
```
Comment (zolotyx) [inline src/app/account/account-sidebar/account-limits/account-limits.component.ts]: think about using getter instead

File: src/app/account/account-sidebar/account-limits/account-limits.component.ts [hunk 3]
```diff
@@ -33,13 +42,42 @@ export class AccountLimitsComponent {
...
+    if (limit.max !== -1) {
+      return limit;
+    }
+    return {
+      ...limit,
+      max: Infinity
+    };
+  }
+
+  private setInfinityToNoLimit(limit: ResourceLimit) {
```
Comment (zolotyx) [inline src/app/account/account-sidebar/account-limits/account-limits.component.ts]: it is no a ResourceLimit if max is not number
