### PR TITLE
(closes #174) Fix insufficient resources error in VM creation

### LINKED ISSUE #174: "Insufficient resources" error when clicking VM creation button
Error message "Insufficient resources"

The most important thing is to describe what exacly is insufficient.

### PR DESCRIPTION
**Pull request by andrewbents**

### CODE REVIEW

File: src/app/vm/vm-creation/vm-creation.component.ts [hunk 1]
```diff
@@ -142,17 +143,22 @@ export class VmCreationComponent implements OnInit {
...
-        ) {
-          this.resetVmCreateData();
-        } else {
-          this.fetching = false;
+        Object.keys(resourceUsage.available)
+          .filter(key => key !== 'snapshots' && key !== 'secondaryStorage')
+          .forEach(key => {
+            const available = resourceUsage.available[key];
+            if (available === 0) {
+              this.insufficientResources.push(key);
```
Comment (zolotyx) [inline src/app/vm/vm-creation/vm-creation.component.ts]: Please create a map where keys are Object.keys(resourceUsage.available) and values are messages not to use resource.toUpperCase() in template
