### PR TITLE
fix(security-group): update filter configuration

### LINKED ISSUE #991: Tabs Domain in VMs and Private SGs in Firewall aren't active after refresh
Steps 
1. Go to Firewall then Private Security Groups tab
2. Refresh page

Expected result: Private SGs tab is active
Actual result: Firewall Templates tab is active

The similar issue happens with Domain tab in VMs
_Before refresh_
domain_is_active
_After refresh_
acount_is_active

**Connected Feature ID:** 
_resourceusage_accountdomain
firewall_list_switch_

### PR DESCRIPTION
**Pull request by tamazlykar**
Fixes #991

### CODE REVIEW

File: src/app/shared/components/vm-statistics/vm-statistics.component.ts [hunk 1]
```diff
@@ -149,6 +149,18 @@ export class VmStatisticsComponent implements OnInit, OnChanges {
       default:
         this.mode = StatsMode.Used;
     }
+
+    const typeRaw = this.storageService.read(statisticsType);
+    switch (parseInt(typeRaw, 10)) {
```
Comment (zolotyx) [inline src/app/shared/components/vm-statistics/vm-statistics.component.ts]: replace with ternary operator
