### PR TITLE
(closes #254): Bug with invisible selected filter fixed

### LINKED ISSUE #254: Event list is empty if localStorage stores type that is not available for current selection
events-filter

### PR DESCRIPTION
**Pull request by zolotyx**

### CODE REVIEW

File: src/app/vm/vm-list/vm-list.component.ts [hunk 1]
```diff
@@ -52,8 +52,8 @@ export class VmListComponent implements OnInit {
   public sections: Array<VmListSection> = [];
   public subsections: Array<VmListSubsection> = [];
 
-  public vmList: Array<VirtualMachine>;
-  public visibleVmList: Array<VirtualMachine>;
+  public vmList: Array<VirtualMachine> = [];
```
Comment (andrewbents) [inline src/app/vm/vm-list/vm-list.component.ts]: there is `*loading="!vmList"` is the template, so it doesn't show a spinner
