### PR TITLE
fix(vm-tags): fix vm tag creation bug (closes #876)

### LINKED ISSUE #876: Error "Invalid resource type undefined" for creating tags
Error "Invalid resource type undefined" appears for creating system and custom tags.
http://cs-ui-ci.z1.netpoint-dc.com:8080/bwsw/master/instances/e76e963b-c54c-404e-8da8-3800d7144542/tags
develop

Steps:
1. Login and press on any VM
2. Go to tags and press add button
3. Fill key and value
4. Press Create

Expected result: tag created
Actual result: Error "Invalid resource type undefined" appear

**Connected feature ID**: vm_tag_create

### PR DESCRIPTION
**Pull request by qqcky**

### CODE REVIEW

File: src/app/template/template-tags/template-tags.component.ts [hunk 1]
```diff
@@ -26,5 +27,13 @@ export class TemplateTagsComponent extends TagsComponent<BaseTemplateModel> {
   ) {
     super(dialogService, tagService);
   }
+
+  public ngOnChanges(changes: SimpleChanges) {
+    if (changes['entity']) {
+      this.resourceType = this.entity.isTemplate
```
Comment (zolotyx) [inline src/app/template/template-tags/template-tags.component.ts]: Please, do not use getter method of the model as we are going to get rid of models.
maybe `this.entity.resourceType || this.resourceType` can be used instead for saving

File: src/app/vm/container/vm-tags.container.ts [hunk 2]
```diff
@@ -12,15 +12,16 @@ import * as vmActions from '../../reducers/vm/redux/vm.actions';
...
       (onTagAdd)="addTag($event)"
       (onTagDelete)="deleteTag($event)"
       (onTagEdit)="editTag($event)"
     ></cs-vm-tags>
   `
 })
 export class VmTagsContainerComponent {
-
   readonly vm$ = this.store.select(fromVMs.getSelectedVM);
+  readonly vmTags$ = this.store.select(fromVMs.getSelectedVmTags);
```
Comment (zolotyx) [inline src/app/vm/container/vm-tags.container.ts]: do we need that?
