### PR TITLE
fix: add query parameter for redirect to shared SG

### LINKED ISSUE #1016: Grouping isn't saved, Delete buttons are absent, redirect to wrong tab when shared SG rules edit through VM sidebar
Steps

1) Log in and go to sidebar of VM with shared security group
2) Open the rule view and select some parameters of grouping
3) Go to rules edit

Expected result: redirect to Shared SGs tab, there are delete buttons, grouping is saved
Actual result: redirect to Firewall Templates tab, there are no delete buttons, grouping isn't saved
(If Shared SGs tab was opened before going to VMs then redirect will be to this tab)

rules view vm
rules edit vm

Connected Feature ID:
vm_firewall_rules_edit

### PR DESCRIPTION
**Pull request by tamazlykar**
Fixes #1016 
But there is another redirect performs after navigating and it takes some time. An issue for this will be created and fixed.

### CODE REVIEW

File: src/app/security-group/sg-rules/sg-rules.component.ts [hunk 1]
```diff
@@ -174,7 +177,10 @@ export class SgRulesComponent implements OnChanges {
               this.router.navigate([
                 'security-group', this.securityGroup.id, 'rules'
               ], {
-                queryParams: { vm: this.vmId }
+                queryParams: {
+                  vm: this.vmId,
+                  viewMode: 'shared'
```
Comment (vanekbr) [inline src/app/security-group/sg-rules/sg-rules.component.ts]: Use enum value here: `viewMode: SecurityGroupViewMode.Shared`

**Comment by tamazlykar** [comment]
@vanekbr fixed :)
