### PR TITLE
(closes #426) Allow admins to view domain statistics

### LINKED ISSUE #426: Add a switch between account and domain resources for Domain admins
Domain account stats display wrong limits (ACS native UI functions the same way). Looks like a bug.
Run on stand UI for room-1/room-1/room-1 credentials to look.

### PR DESCRIPTION
**Pull request by andrewbents**

### CODE REVIEW

File: src/app/shared/components/vm-statistics/vm-statistics.component.ts [hunk 1]
```diff
@@ -130,24 +144,44 @@ export class VmStatisticsComponent implements OnInit {
     }
   }
 
+  public get isAdmin(): boolean {
+    return this.authService.user.type !== AccountType.User;
```
Comment (zolotyx) [inline src/app/shared/components/vm-statistics/vm-statistics.component.ts]: Move this to authService

**Comment by zolotyx** [comment]
@andrewbents , please switch Available/Used and Account/Domain widgets

File: src/app/shared/services/auth.service.ts [hunk 2]
```diff
@@ -136,69 +67,22 @@ export class AuthService extends BaseBackendService<BaseModelStub> {
   }
 
   public isLoggedIn(): Observable<boolean> {
-    return Observable.of(!!this.userId);
+    return Observable.of(!!(this._user && this._user.userId));
   }
 
-  public sendRefreshRequest(): void {
-    this.userService.getList().subscribe();
+  public isAdmin(): boolean {
```
Comment (wowshakhov) [inline src/app/shared/services/auth.service.ts]: maybe public get isAdmin()?
